# dlm-photo-gallery-v2 specific overrides
# Use with: docker compose -f ../../vadimOS/docker/docker-compose.base.yml -f docker-compose.yml

services:
  db:
    environment:
      - POSTGRES_DB=dlm-photo-gallery-v2